//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATIVIDADE
    {
        public int ID_ATIVIDADE { get; set; }
        public int ID_TIPO_ATIVIDADE { get; set; }
        public System.DateTime DT_CRIACAO_ATIVIDADE { get; set; }
        public Nullable<System.DateTime> DT_RECEBIMENTO_ATIVIDADE { get; set; }
        public int ID_USUARIO { get; set; }
    }
}
