//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMISSAO_DISCIPLINAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMISSAO_DISCIPLINAR()
        {
            this.COMISSAO_DISCIPLINAR_PROCESSO = new HashSet<COMISSAO_DISCIPLINAR_PROCESSO>();
        }
    
        public int ID_COMISSAO_DISCIPLINAR { get; set; }
        public int ID_LOCAL_ORGAO { get; set; }
        public string SG_UF { get; set; }
        public string DS_ENDERECO { get; set; }
        public string NR_TELEFONE { get; set; }
        public string DS_EMAIL { get; set; }
        public string DS_UNIDADE_SEI { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO_REGISTRO { get; set; }
        public Nullable<int> ID_USUARIO_EXCLUSAO { get; set; }
    
        public virtual LOCAL_ORGAO LOCAL_ORGAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMISSAO_DISCIPLINAR_PROCESSO> COMISSAO_DISCIPLINAR_PROCESSO { get; set; }
    }
}
