//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORREICAO
    {
        public int ID_CORREICAO { get; set; }
        public int ID_PROCESSO { get; set; }
        public string TP_ESPECIE_CORREICAO { get; set; }
        public int ID_UNIDADE_CORREICIONADA { get; set; }
        public int ID_OBJETO { get; set; }
        public Nullable<System.DateTime> DT_INICIO_CORREICAO { get; set; }
        public Nullable<System.DateTime> DT_FIM_CORREICAO { get; set; }
        public string NR_PORTATIA { get; set; }
        public System.DateTime DT_PUBLICACAO_PORTARIA { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO_REGISTRO { get; set; }
        public Nullable<int> ID_USUARIO_EXCLUSAO { get; set; }
    
        public virtual OBJETO OBJETO { get; set; }
        public virtual PROCESSO PROCESSO { get; set; }
    }
}
