//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECISAO_JUDICIAL
    {
        public int ID_DECISAO_JUDICIAL { get; set; }
        public int ID_PROCESSO { get; set; }
        public int ID_TIPO_DECISAO { get; set; }
        public int ID_CONTEUDO_DECISAO { get; set; }
        public int ID_ORGAO_PROLATOR { get; set; }
        public string DS_DECISAO_JUDICIAL { get; set; }
        public System.DateTime DT_INTIMACAO { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO_REGISTRO { get; set; }
        public Nullable<int> ID_USUARIO_EXCLUSAO { get; set; }
    
        public virtual CONTEUDO_DECISAO CONTEUDO_DECISAO { get; set; }
        public virtual ORGAO_PROLATOR ORGAO_PROLATOR { get; set; }
        public virtual PROCESSO PROCESSO { get; set; }
        public virtual TIPO_DECISAO TIPO_DECISAO { get; set; }
    }
}
