//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBUICAO_PROCESSO
    {
        public int ID_DISTRIBUICAO_PROCESSO { get; set; }
        public int ID_ANDAMENTO_PROCESSO { get; set; }
        public int ID_SERVIDOR { get; set; }
        public int QT_DIA_PRAZO { get; set; }
        public System.DateTime DT_DISTRIBUICAO { get; set; }
        public System.DateTime DT_PREVISAO_ENTREGA { get; set; }
        public Nullable<System.DateTime> DT_CONCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_ENCAMINHAMENTO_RESPOSTA { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO_REGISTRO { get; set; }
        public Nullable<int> ID_USUARIO_EXCLUSAO { get; set; }
    
        public virtual ANDAMENTO_PROCESSO ANDAMENTO_PROCESSO { get; set; }
    }
}
