//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENDERECO_COMISSAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENDERECO_COMISSAO()
        {
            this.PROCESSO_ADMINISTRATIVO_DISCIPLINAR = new HashSet<PROCESSO_ADMINISTRATIVO_DISCIPLINAR>();
        }
    
        public int ID_ENDERECO_COMISSAO { get; set; }
        public string DS_ENDERECO_COMISSAO { get; set; }
        public System.DateTime DT_INICIO_VIGENCIA { get; set; }
        public Nullable<System.DateTime> DT_FIM_VIGENCIA { get; set; }
        public string SN_REGISTRO_ATIVO { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO_REGISTRO { get; set; }
        public Nullable<int> ID_USUARIO_EXCLUSAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESSO_ADMINISTRATIVO_DISCIPLINAR> PROCESSO_ADMINISTRATIVO_DISCIPLINAR { get; set; }
    }
}
