//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENVOLVIDO_PROCESSO
    {
        public int ID_ENVOLVIDO_PROCESSO { get; set; }
        public Nullable<int> ID_PESSOA_ENVOLVIDA { get; set; }
        public int ID_TIPO_ENVOLVIMENTO { get; set; }
        public Nullable<int> ID_PROCESSO { get; set; }
        public Nullable<int> ID_PROCESSO_PORTARIA { get; set; }
        public bool FG_ENVOLVIDO_IDENTIFICADO { get; set; }
        public Nullable<bool> FG_ESTAGIO_PROBATORIO { get; set; }
        public bool FG_REGISTRO_EXCLUIDO { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO_REGISTRO { get; set; }
        public Nullable<int> ID_USUARIO_EXCLUSAO { get; set; }
    
        public virtual PROCESSO PROCESSO { get; set; }
        public virtual PROCESSO_PORTARIA PROCESSO_PORTARIA { get; set; }
        public virtual TIPO_ENVOLVIMENTO TIPO_ENVOLVIMENTO { get; set; }
    }
}
