//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASE_PROCESSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FASE_PROCESSO()
        {
            this.FASE_ATO_PROCESSO = new HashSet<FASE_ATO_PROCESSO>();
        }
    
        public int ID_FASE_PROCESSO { get; set; }
        public string DS_FASE_PROCESSO { get; set; }
        public int NR_ORDEM_FASE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FASE_ATO_PROCESSO> FASE_ATO_PROCESSO { get; set; }
    }
}
