//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBJETO()
        {
            this.CORREICAOs = new HashSet<CORREICAO>();
            this.DEMANDA_ESPECIAL = new HashSet<DEMANDA_ESPECIAL>();
            this.OBJETO_TIPO_PROCESSO = new HashSet<OBJETO_TIPO_PROCESSO>();
            this.PROCESSOes = new HashSet<PROCESSO>();
        }
    
        public int ID_OBJETO { get; set; }
        public string DS_OBJETO { get; set; }
        public System.DateTime DT_INICIO_VIGENCIA { get; set; }
        public Nullable<System.DateTime> DT_FIM_VIGENCIA { get; set; }
        public string SN_REGISTRO_ATIVO { get; set; }
        public Nullable<int> ID_USUARIO_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO_REGISTRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORREICAO> CORREICAOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEMANDA_ESPECIAL> DEMANDA_ESPECIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBJETO_TIPO_PROCESSO> OBJETO_TIPO_PROCESSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESSO> PROCESSOes { get; set; }
    }
}
