//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETO_TIPO_PROCESSO
    {
        public int ID_OBJETO_TIPO_PROCESSO { get; set; }
        public int ID_OBJETO { get; set; }
        public int ID_TIPO_PROCESSO { get; set; }
    
        public virtual OBJETO OBJETO { get; set; }
        public virtual TIPO_PROCESSO TIPO_PROCESSO { get; set; }
    }
}
