//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSO_ADMINISTRATIVO_GERAL
    {
        public int ID_PROCESSO_ADMINISTRATIVO_GERAL { get; set; }
        public int ID_PROCESSO { get; set; }
        public string TP_INTERESSADO { get; set; }
        public string DS_ASSUNTO { get; set; }
        public System.DateTime DT_RECEBIMENTO { get; set; }
        public Nullable<int> ID_USUARIO_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO_REGISTRO { get; set; }
    
        public virtual PROCESSO PROCESSO { get; set; }
    }
}
