//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROCESSO()
        {
            this.ANDAMENTO_PROCESSO = new HashSet<ANDAMENTO_PROCESSO>();
            this.COMISSAO_DISCIPLINAR_PROCESSO = new HashSet<COMISSAO_DISCIPLINAR_PROCESSO>();
            this.CORREICAOs = new HashSet<CORREICAO>();
            this.DECISAO_JUDICIAL = new HashSet<DECISAO_JUDICIAL>();
            this.DEMANDA_ESPECIAL = new HashSet<DEMANDA_ESPECIAL>();
            this.ENVOLVIDO_PROCESSO = new HashSet<ENVOLVIDO_PROCESSO>();
            this.INTERESSADOes = new HashSet<INTERESSADO>();
            this.JULGAMENTOes = new HashSet<JULGAMENTO>();
            this.PEDIDO_CERTIDAO = new HashSet<PEDIDO_CERTIDAO>();
            this.PROCESSO_ADMINISTRATIVO_DISCIPLINAR = new HashSet<PROCESSO_ADMINISTRATIVO_DISCIPLINAR>();
            this.PROCESSO_ADMINISTRATIVO_GERAL = new HashSet<PROCESSO_ADMINISTRATIVO_GERAL>();
            this.PROCESSO_PORTARIA = new HashSet<PROCESSO_PORTARIA>();
            this.PROCESSO_RELACIONADO = new HashSet<PROCESSO_RELACIONADO>();
            this.PROCESSO_RELACIONADO1 = new HashSet<PROCESSO_RELACIONADO>();
            this.RELATORIO_FINAL = new HashSet<RELATORIO_FINAL>();
            this.SUSPENSAO_PRESCRICAO = new HashSet<SUSPENSAO_PRESCRICAO>();
        }
    
        public int ID_PROCESSO { get; set; }
        public int ID_TIPO_PROCESSO { get; set; }
        public string NR_PROCESSO { get; set; }
        public Nullable<int> ID_OBJETO { get; set; }
        public Nullable<int> ID_ESPECIE { get; set; }
        public string TP_ARMAZENAMENTO { get; set; }
        public Nullable<System.DateTime> DT_RECEBIMENTO { get; set; }
        public Nullable<System.DateTime> DT_CONHECIMENTO_FATO { get; set; }
        public Nullable<System.DateTime> DT_INSTAURACAO { get; set; }
        public Nullable<System.DateTime> DT_ADVERTENCIA { get; set; }
        public Nullable<System.DateTime> DT_SUSPENSAO { get; set; }
        public Nullable<System.DateTime> DT_DEMISSAO { get; set; }
        public Nullable<System.DateTime> DT_CONCLUSAO { get; set; }
        public System.DateTime DT_INICIO_VIGENCIA { get; set; }
        public Nullable<System.DateTime> DT_FIM_VIGENCIA { get; set; }
        public string SN_REGISTRO_ATIVO { get; set; }
        public Nullable<int> ID_USUARIO_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO_REGISTRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANDAMENTO_PROCESSO> ANDAMENTO_PROCESSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMISSAO_DISCIPLINAR_PROCESSO> COMISSAO_DISCIPLINAR_PROCESSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORREICAO> CORREICAOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECISAO_JUDICIAL> DECISAO_JUDICIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEMANDA_ESPECIAL> DEMANDA_ESPECIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENVOLVIDO_PROCESSO> ENVOLVIDO_PROCESSO { get; set; }
        public virtual ESPECIE ESPECIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERESSADO> INTERESSADOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JULGAMENTO> JULGAMENTOes { get; set; }
        public virtual OBJETO OBJETO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO_CERTIDAO> PEDIDO_CERTIDAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESSO_ADMINISTRATIVO_DISCIPLINAR> PROCESSO_ADMINISTRATIVO_DISCIPLINAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESSO_ADMINISTRATIVO_GERAL> PROCESSO_ADMINISTRATIVO_GERAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESSO_PORTARIA> PROCESSO_PORTARIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESSO_RELACIONADO> PROCESSO_RELACIONADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESSO_RELACIONADO> PROCESSO_RELACIONADO1 { get; set; }
        public virtual TIPO_PROCESSO TIPO_PROCESSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELATORIO_FINAL> RELATORIO_FINAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUSPENSAO_PRESCRICAO> SUSPENSAO_PRESCRICAO { get; set; }
    }
}
