//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSO_ADMINISTRATIVO_DISCIPLINAR
    {
        public int ID_PROCESSO_ADMINISTRATIVO_DISCIPLINAR { get; set; }
        public int ID_PROCESSO { get; set; }
        public string NR_PROCESSO_APOIO_COMISSAO { get; set; }
        public Nullable<int> ID_ENDERECO_COMISSAO { get; set; }
        public string TX_OBSERVACAO { get; set; }
        public Nullable<int> ID_PROCESSO_NEGOCIO { get; set; }
        public Nullable<int> ID_USUARIO_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO_REGISTRO { get; set; }
    
        public virtual ENDERECO_COMISSAO ENDERECO_COMISSAO { get; set; }
        public virtual PROCESSO PROCESSO { get; set; }
        public virtual PROCESSO_NEGOCIO PROCESSO_NEGOCIO { get; set; }
    }
}
