//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SICCOR_APLICACAO_LOG
    {
        public int ID_APPLOG { get; set; }
        public System.DateTime DT_OCORRENCIA { get; set; }
        public string DS_PONTO_OCORRENCIA { get; set; }
        public string DS_NIVEL_OCORRENCIA { get; set; }
        public string DS_USUARIO_LOGIN { get; set; }
        public string DS_MENSAGEM { get; set; }
        public string DS_EXCECAO { get; set; }
    }
}
