//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SICCOREntities : DbContext
    {
        public SICCOREntities()
            : base("name=SICCOREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANDAMENTO_PROCESSO> ANDAMENTO_PROCESSO { get; set; }
        public virtual DbSet<ATIVIDADE> ATIVIDADEs { get; set; }
        public virtual DbSet<ATO_PRATICADO> ATO_PRATICADO { get; set; }
        public virtual DbSet<ATO_PROCESSO> ATO_PROCESSO { get; set; }
        public virtual DbSet<AUTORIDADE> AUTORIDADEs { get; set; }
        public virtual DbSet<COMISSAO_DISCIPLINAR> COMISSAO_DISCIPLINAR { get; set; }
        public virtual DbSet<COMISSAO_DISCIPLINAR_PROCESSO> COMISSAO_DISCIPLINAR_PROCESSO { get; set; }
        public virtual DbSet<CONTEUDO_DECISAO> CONTEUDO_DECISAO { get; set; }
        public virtual DbSet<CORREICAO> CORREICAOs { get; set; }
        public virtual DbSet<DECISAO_JUDICIAL> DECISAO_JUDICIAL { get; set; }
        public virtual DbSet<DEMANDA_ESPECIAL> DEMANDA_ESPECIAL { get; set; }
        public virtual DbSet<DISTRIBUICAO_PROCESSO> DISTRIBUICAO_PROCESSO { get; set; }
        public virtual DbSet<ENDERECO_COMISSAO> ENDERECO_COMISSAO { get; set; }
        public virtual DbSet<ENVOLVIDO_PROCESSO> ENVOLVIDO_PROCESSO { get; set; }
        public virtual DbSet<ESPECIE> ESPECIEs { get; set; }
        public virtual DbSet<FASE_ATO_PROCESSO> FASE_ATO_PROCESSO { get; set; }
        public virtual DbSet<FASE_PROCESSO> FASE_PROCESSO { get; set; }
        public virtual DbSet<INTERESSADO> INTERESSADOes { get; set; }
        public virtual DbSet<JULGAMENTO> JULGAMENTOes { get; set; }
        public virtual DbSet<LOCAL_ORGAO> LOCAL_ORGAO { get; set; }
        public virtual DbSet<MEIO_PUBLICACAO> MEIO_PUBLICACAO { get; set; }
        public virtual DbSet<OBJETO> OBJETOes { get; set; }
        public virtual DbSet<OBJETO_TIPO_PROCESSO> OBJETO_TIPO_PROCESSO { get; set; }
        public virtual DbSet<ORGAO> ORGAOs { get; set; }
        public virtual DbSet<ORGAO_EXTERNO> ORGAO_EXTERNO { get; set; }
        public virtual DbSet<ORGAO_PROLATOR> ORGAO_PROLATOR { get; set; }
        public virtual DbSet<PEDIDO_CERTIDAO> PEDIDO_CERTIDAO { get; set; }
        public virtual DbSet<PROCESSO> PROCESSOes { get; set; }
        public virtual DbSet<PROCESSO_ADMINISTRATIVO_DISCIPLINAR> PROCESSO_ADMINISTRATIVO_DISCIPLINAR { get; set; }
        public virtual DbSet<PROCESSO_ADMINISTRATIVO_GERAL> PROCESSO_ADMINISTRATIVO_GERAL { get; set; }
        public virtual DbSet<PROCESSO_NEGOCIO> PROCESSO_NEGOCIO { get; set; }
        public virtual DbSet<PROCESSO_PORTARIA> PROCESSO_PORTARIA { get; set; }
        public virtual DbSet<PROCESSO_RELACIONADO> PROCESSO_RELACIONADO { get; set; }
        public virtual DbSet<RELATORIO_FINAL> RELATORIO_FINAL { get; set; }
        public virtual DbSet<SICCOR_APLICACAO_LOG> SICCOR_APLICACAO_LOG { get; set; }
        public virtual DbSet<SUSPENSAO_PRESCRICAO> SUSPENSAO_PRESCRICAO { get; set; }
        public virtual DbSet<TIPO_ATIVIDADE> TIPO_ATIVIDADE { get; set; }
        public virtual DbSet<TIPO_CONTEUDO_DECISAO> TIPO_CONTEUDO_DECISAO { get; set; }
        public virtual DbSet<TIPO_DECISAO> TIPO_DECISAO { get; set; }
        public virtual DbSet<TIPO_ENVOLVIMENTO> TIPO_ENVOLVIMENTO { get; set; }
        public virtual DbSet<TIPO_JULGAMENTO> TIPO_JULGAMENTO { get; set; }
        public virtual DbSet<TIPO_PORTARIA> TIPO_PORTARIA { get; set; }
        public virtual DbSet<TIPO_PROCESSO> TIPO_PROCESSO { get; set; }
    }
}
