//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSPENSAO_PRESCRICAO
    {
        public int ID_SUSPENSAO_PRESCRICAO { get; set; }
        public int ID_PROCESSO { get; set; }
        public System.DateTime DT_INICIO_SUSPENSAO_PRESCRICAO { get; set; }
        public Nullable<System.DateTime> DT_FIM_SUSPENSAO_PRESCRICAO { get; set; }
        public Nullable<System.DateTime> DT_ADVERTENCIA { get; set; }
        public Nullable<System.DateTime> DT_SUSPENSAO { get; set; }
        public Nullable<System.DateTime> DT_DEMISSAO { get; set; }
        public string DS_SUSPENSAO_PRESCRICAO { get; set; }
        public int ID_USUARIO_RESPONSAVEL { get; set; }
        public System.DateTime DT_CADASTRAMENTO_SUSPENSAO { get; set; }
        public Nullable<int> ID_USUARIO_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_EXCLUSAO_REGISTRO { get; set; }
    
        public virtual PROCESSO PROCESSO { get; set; }
    }
}
