//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ENVOLVIMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_ENVOLVIMENTO()
        {
            this.ENVOLVIDO_PROCESSO = new HashSet<ENVOLVIDO_PROCESSO>();
        }
    
        public int ID_TIPO_ENVOLVIMENTO { get; set; }
        public string DS_TIPO_ENVOLVIMENTO { get; set; }
        public System.DateTime DT_INICIO_VIGENCIA { get; set; }
        public Nullable<System.DateTime> DT_FIM_VIGENCIA { get; set; }
        public string SN_REGISTRO_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENVOLVIDO_PROCESSO> ENVOLVIDO_PROCESSO { get; set; }
    }
}
