//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anac.DataModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ATIVIDADE
    {
        public int ID_TIPO_ATIVIDADE { get; set; }
        public string DS_ATIVIDADE { get; set; }
    }
}
